version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-github
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./../../jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=--httpPort=8080
    user: root
