# Kind cluster configuration with registry mirrors
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: sical-cluster

# 网络配置
networking:
  disableDefaultCNI: false
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  apiServerPort: 6443

# 节点配置
nodes:
# 控制平面节点
- role: control-plane
  image: kindest/node:v1.28.0
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  - containerPort: 5000
    hostPort: 5000
    protocol: TCP
  extraMounts:
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock

# 工作节点
- role: worker
  image: kindest/node:v1.28.0
  extraMounts:
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock

- role: worker
  image: kindest/node:v1.28.0
  extraMounts:
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock

# 容器运行时配置 - 配置多个镜像源
containerdConfigPatches:
- |
  [plugins."io.containerd.grpc.v1.cri".registry]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
        endpoint = [
          "https://dockerproxy.com",
          "https://docker.mirrors.ustc.edu.cn",
          "https://mirror.baidubce.com",
          "https://ccr.ccs.tencentyun.com",
          "https://registry.docker-cn.com",
          "https://docker.io"
        ]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."k8s.gcr.io"]
        endpoint = [
          "https://k8s-gcr-io.mirrors.ustc.edu.cn",
          "https://k8s.gcr.io"
        ]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.k8s.io"]
        endpoint = [
          "https://k8s-gcr-io.mirrors.ustc.edu.cn",
          "https://registry.k8s.io"
        ]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."quay.io"]
        endpoint = [
          "https://quay-mirror.qiniu.com",
          "https://quay.io"
        ]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
        endpoint = ["http://localhost:5000"]
