apiVersion: v1
kind: Namespace
metadata:
  name: sical
  labels:
    name: sical
    environment: development
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: sical-quota
  namespace: sical
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: sical-limits
  namespace: sical
spec:
  limits:
  - default:
      cpu: "200m"
      memory: "256Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container